name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Download and install cloudflared
      run: |
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared.deb
        sudo cloudflared service install eyJhIjoiNTMwMDc3YmZlY2VkMmFiN2NjZTQ3NDEzYTY5MTFiYWQiLCJ0IjoiMmQ3YzUwMWQtZmRkZi00OWI3LWE0YzgtZGViODI5Yjg3YWMyIiwicyI6Ik1HSmpaamxqTnpBdE16QmhNaTAwWkRrNExXRXdZMlF0WmpneE1XSTBNREF5T1RabSJ9

    - name: Keep workflow running
      run: sleep infinity
