name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Install ngrok
      run: |
         sudo apt install sshpass -y
         sshpass -p "segfault" ssh -R 5555:localhost:22 -o 'SetEnv SECRET=GmjQJUzkNWULszMrrBNiuYYJ' root@lulz.segfault.net
         
