name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Download and install cloudflared
      run: |
        docker run --rm --net=host -e SECRET_KEY=72d553bd996951da4b4a9ebf0307e3c455fd69a77c9bda91d57a5fba067064b0 ghcr.io/playit-cloud/playit-agent:0.15
