name: Change Password and Run Ngrok

on:
  push:
    branches:
      - main

jobs:
  change_password_and_run_ngrok:
    runs-on: ubuntu-latest
    steps:
    - name: Change Password
      run: echo -e "123456a\n123456a" | sudo passwd $(whoami)

    - name: Start SSH service
      run: sudo service ssh start

    - name: Add SSH host key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H lulz.segfault.net >> ~/.ssh/known_hosts

    - name: Forward port 22 to 5555 and keep SSH open
      run: |
        nohup sshpass -p "segfault" ssh -N -R 5555:localhost:22 -o 'SetEnv SECRET=AeLXKDVYKIUVvZfksSklcsiK' root@lulz.segfault.net &
        sleep infinity
